import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";
import { ReactNode, useMemo } from "react";
import Navigation from "./components/navigation";

const unbounded = Unbounded ({
  subsets: ["latin"],
  weight: ["200", "300"],
  variable: "--font-unbounded",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${unbounded.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navigation>
          {children}
        </Navigation>
        </body>
    </html>
  );
}
