import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";
import { ReactNode} from "react";
import Navigation from "./components/networkSelector";
import Providers from "./components/providers";
import NetworkSelector from "./components/networkSelector";
import AppWrapper from "./components/appWrapper";

const unbounded = Unbounded ({
  subsets: ["latin"],
  weight: ["200", "300"],
  variable: "--font-unbounded",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${unbounded.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="h-full w-full flex flex-col">
          <AppWrapper> 
            {children}
          </AppWrapper> 
        </body>
    </html>
  );
}
